// Zentrales Manifest der 4 Präsentations-Vorlagen.
// Wird sowohl vom Frontend (Schritt 1 Karten, Schritt 2 Formularfelder) als auch
// von api/generate-presentation.js und api/deploy-presentation.js genutzt.
const TEMPLATES = [
  {
    id: 'neukunden-demo-b2b',
    label: 'Neukunden-Demo B2B',
    description: 'Erstpräsentation für Neukunden – vollständige Produktvorstellung mit Video-Demos.',
    file: 'templates/neukunden-demo-b2b.html',
    assetDir: 'templates/assets/neukunden-demo-b2b',
    extraFields: [], // keine template-spezifischen Zusatzfelder
    staticAssets: [
      'Large.svg',
      'Girl with VR.jpg',
      'Dein-Erster-Tag-Medienbox-1024x692.webp',
      'Berufsberatung.jpg',
      'ElevenLabs_2026-05-28T11_11_39_Yvonne_gen_sp100_s80_sb60_v3.mp3',
      'kurzfilm-kino-feed.png',
      'Minigames.png',
      'Azubichat.png',
      'Schulkarte.png',
      'jobapp.png',
      'Mini_Games_NEU.mp4',
      'Azubi_Chat_NEU.mp4',
      'AR.mp4',
      'VR Magic.png',
      'Thumbnail YT 1.png',
      'Thumbnail YT 2.png',
      'Thumbnail YT 3.png',
      'Thumbnail YT 4.png',
      'Thumbnail YT 5.png',
      'Thumbnail YT 6.png',
      'Thumbnail YT 7.png',
      'Thumbnail YT 8.png',
    ],
  },
  {
    id: 'bestandskunden-nur-app',
    label: 'Bestandskunden: Nur App',
    description: 'Für Bestandskunden mit JobApp – Upsell auf das neue Employer-Branding-Angebot.',
    file: 'templates/bestandskunden-nur-app.html',
    assetDir: 'templates/assets/bestandskunden-nur-app',
    extraFields: ['contractPrice', 'contractEndDate', 'arProdCost', 'arMarketingCost'],
    staticAssets: [
      'Large.svg',
      'jobapp.png',
      'Bild1.jpg',
      'Dein-Erster-Tag-Medienbox-1024x692.webp',
      'Minigames.png',
      'Azubichat.png',
      'Thumbnail YT 1.png',
      'Thumbnail YT 2.png',
      'Thumbnail YT 3.png',
      'Thumbnail YT 4.png',
      'Thumbnail YT 5.png',
      'Thumbnail YT 6.png',
      'Thumbnail YT 7.png',
      'Thumbnail YT 8.png',
      'eileen-byrne-1_u5U9UvA1s-unsplash.jpg',
      'Medienbox Magic 2.png',
      'Medienbox 4.png',
      'Schulportal.png',
      'Mini_Games_NEU.mp4',
      'Azubi_Chat_NEU.mp4',
      'AR.mp4',
      'VR Magic.png',
    ],
  },
  {
    id: 'bestandskunden-nur-sv',
    label: 'Bestandskunden: Nur SV',
    description: 'Für Bestandskunden ohne JobApp – Fokus auf Schulvermarktung.',
    file: 'templates/bestandskunden-nur-sv.html',
    assetDir: 'templates/assets/bestandskunden-nur-sv',
    extraFields: ['arProdCost', 'arMarketingCost'],
    staticAssets: [
      'Bild1.jpg',
      'Schulportal.png',
      'Dein-Erster-Tag-Medienbox-1024x692.webp',
      'Siemens 1.png',
      'Arbeitskleidung.png',
      'Minigames.png',
      'Azubichat.png',
      'Thumbnail YT 1.png',
      'Thumbnail YT 2.png',
      'Thumbnail YT 3.png',
      'Thumbnail YT 4.png',
      'Thumbnail YT 5.png',
      'Thumbnail YT 6.png',
      'Thumbnail YT 7.png',
      'Thumbnail YT 8.png',
      'eileen-byrne-1_u5U9UvA1s-unsplash.jpg',
      'Large.svg',
      'Medienbox 4.png',
      'Medienbox Magic 3.png',
      'Mini_Games_NEU.mp4',
      'Azubi_Chat_NEU.mp4',
      'VR Magic.png',
      'AR.mp4',
    ],
  },
  {
    id: 'bestandskunden-app-sv',
    label: 'Bestandskunden: App + SV',
    description: 'Für Bestandskunden mit JobApp UND Schulvermarktung – das Gesamtpaket.',
    file: 'templates/bestandskunden-app-sv.html',
    assetDir: 'templates/assets/bestandskunden-app-sv',
    extraFields: ['arProdCost', 'arMarketingCost'],
    staticAssets: [
      'Bild1.jpg',
      'Dein-Erster-Tag-Medienbox-1024x692.webp',
      'Siemens 1.png',
      'Arbeitskleidung.png',
      'Minigames.png',
      'Azubichat.png',
      'Thumbnail YT 1.png',
      'Thumbnail YT 2.png',
      'Thumbnail YT 3.png',
      'Thumbnail YT 4.png',
      'Thumbnail YT 5.png',
      'Thumbnail YT 6.png',
      'Thumbnail YT 7.png',
      'Thumbnail YT 8.png',
      'eileen-byrne-1_u5U9UvA1s-unsplash.jpg',
      'Large.svg',
      'Medienbox 4.png',
      'Medienbox Magic 3.png',
      'Mini_Games_NEU.mp4',
      'Azubi_Chat_NEU.mp4',
      'VR Magic.png',
      'AR.mp4',
    ],
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TEMPLATES };
}
